cxx_library(
  name = 'test',
  header_namespace = '',
  exported_headers = subdir_glob([
    ('source', '**/*.h'),
  ]),
  srcs = glob([
    'source/**/*.cpp',
  ], excludes = [
    'source/main.cpp',
  ]),
  deps = [
    '//:eastl',
    '//test/packages/EAAssert:eaassert',
    '//test/packages/EABase:eabase',
    '//test/packages/EAMain:eamain',
    '//test/packages/EAStdC:eastdc',
    '//test/packages/EATest:eatest',
    '//test/packages/EAThread:eathread',
  ],
  visibility = [
    'PUBLIC', 
  ], 
)

cxx_binary(
  name = 'test-runner',
  srcs = glob([
    'source/main.cpp',
  ]),
  deps = [
    ':test',
  ],
)
